### ISSUE TITLE
Trace dump during a local test deployment

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/appengine#27] opened 2015-01-20 04:41 UTC
ERROR: Error building docker image XXXXXX
ERROR: Build Error: The command [/bin/sh -c pub get] returned a non-zero code: 69.
ERROR: Full Image Build Log:
# Executing 4 build triggers
Trigger 0, ADD pubspec.* /app/
Step 0 : ADD pubspec.* /app/
 ---> Using cache
Trigger 1, RUN pub get
Step 0 : RUN pub get
 ---> Running in 54e19161048c
Resolving dependencies...
Downloading appengine 0.2.5...
Downloading gcloud 0.1.3+1...
Downloading mustache 0.1.8...
Downloading fixnum 0.9.1...
Downloading googleapis_auth 0.2.2...
Downloading http_server 0.9.5+1...
Downloading memcache 0.1.0...
Downloading path 1.3.1...
Downloading protobuf 0.3.4...
Downloading crypto 0.9.0...
Downloading googleapis 0.5.4...
Downloading googleapis_beta 0.5.2...
Downloading http 0.11.1+1...
Downloading mime 0.9.1...
Downloading http_parser 0.0.2+5...
Downloading stack_trace 1.1.1...
Downloading collection 1.1.0...
Downloading string_scanner 0.1.3...
Downloading source_span 1.0.2...
tar: LICENSE: time stamp 2015-01-19 08:46:15 is 404520.149026615 s in the future
tar: lib/groupssettings/v1.dart: time stamp 2015-01-19 08:46:15 is 404520.14827709 s in the future
tar: lib/siteverification/v1.dart: time stamp 2015-01-19 08:46:14 is 404519.148194529 s in the future
tar: lib/content/v2.dart: time stamp 2015-01-19 08:46:15 is 404520.147139015 s in the future
tar: lib/analytics/v3.dart: time stamp 2015-01-19 08:46:15 is 404498.241021698 s in the future
tar: lib/books/v1.dart: time stamp 2015-01-19 08:46:15 is 404487.264255843 s in the future
tar: lib/adexchangeseller/v2_0.dart: time stamp 2015-01-19 08:46:15 is 404487.264016072 s in the future
tar: lib/adexchangeseller/v1_1.dart: time stamp 2015-01-19 08:46:14 is 404486.263815428 s in the future
tar: lib/dfareporting/v1_3.dart: time stamp 2015-01-19 08:46:14 is 404474.754427048 s in the future
tar: lib/dfareporting/v2_0.dart: time stamp 2015-01-19 08:46:15 is 404435.381761157 s in the future
tar: lib/qpxexpress/v1.dart: time stamp 2015-01-19 08:46:14 is 404434.379757733 s in the future
tar: lib/src/common_internal.dart: time stamp 2015-01-19 08:46:14 is 404434.379324958 s in the future
tar: lib/youtubeanalytics/v1.dart: time stamp 2015-01-19 08:46:14 is 404413.478663098 s in the future
tar: lib/blogger/v3.dart: time stamp 2015-01-19 08:46:15 is 404414.478144121 s in the future
tar: lib/gamesmanagement/v1management.dart: time stamp 2015-01-19 08:46:15 is 404414.477900375 s in the future
tar: lib/doubleclicksearch/v2.dart: time stamp 2015-01-19 08:46:15 is 404414.477593803 s in the future
tar: lib/civicinfo/v1.dart: time stamp 2015-01-19 08:46:14 is 404400.5044548 s in the future
tar: lib/civicinfo/v2.dart: time stamp 2015-01-19 08:46:15 is 404401.504172867 s in the future
tar: lib/civicinfo/us_v1.dart: time stamp 2015-01-19 08:46:15 is 404401.503996855 s in the future
tar: lib/storage/v1.dart: time stamp 2015-01-19 08:46:15 is 404401.503388012 s in the future
tar: lib/compute/v1.dart: time stamp 2015-01-19 08:46:15 is 404376.232290538 s in the future
tar: lib/tagmanager/v1.dart: time stamp 2015-01-19 08:46:15 is 404362.830151451 s in the future
tar: lib/androidpublisher/v2.dart: time stamp 2015-01-19 08:46:15 is 404362.829377748 s in the future
tar: lib/appsactivity/v1.dart: time stamp 2015-01-19 08:46:15 is 404362.829064954 s in the future
tar: lib/webfonts/v1.dart: time stamp 2015-01-19 08:46:15 is 404362.828880488 s in the future
tar: lib/fusiontables/v1.dart: time stamp 2015-01-19 08:46:15 is 404362.826310124 s in the future
tar: lib/fusiontables/v2.dart: time stamp 2015-01-19 08:46:15 is 404327.813566856 s in the future
tar: lib/oauth2/v2.dart: time stamp 2015-01-19 08:46:15 is 404327.813313702 s in the future
tar: lib/freebase/v1.dart: time stamp 2015-01-19 08:46:15 is 404327.812457121 s in the future
tar: lib/drive/v2.dart: time stamp 2015-01-19 08:46:15 is 404304.840586122 s in the future
tar: lib/adexchangebuyer/v1_3.dart: time stamp 2015-01-19 08:46:15 is 404304.838827977 s in the future
tar: lib/reseller/v1.dart: time stamp 2015-01-19 08:46:15 is 404304.838584795 s in the future
Connection closed while receiving data

ERROR: Internal error while starting instance.
Traceback (most recent call last):
  File "/Users/lukechurch/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/module.py", line 1823, in _start_instance
    if not inst.start():
  File "/Users/lukechurch/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/instance.py", line 274, in start
    self._runtime_proxy.start()
  File "/Users/lukechurch/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/vm_runtime_proxy.py", line 292, in start
    self._container.Start()
  File "/Users/lukechurch/google-cloud-sdk/platform/google_appengine/google/appengine/tools/docker/containers.py", line 480, in Start
    self._image.Build()
  File "/Users/lukechurch/google-cloud-sdk/platform/google_appengine/google/appengine/tools/docker/containers.py", line 265, in Build
    raise ImageError

**Comment by mkustermann** [comment] 2015-01-20 08:57
Could you check the clock inside the VirtualBox?

$ boot2docker ssh
boot2docker $ date

If it is wrong, you can just correct it with the same `date` command.

I assume that the clock inside the VirtualBox VM is wrong. It is a known issue that putting a MacBook to sleep mode stops the clock inside the VirtualBox VM. The package it is complaining about is `googleapis` which got updated yesterday.

**Comment by mkustermann** [comment] 2015-02-20 12:22
The fact that the docker image cannot be built, seems to be caused by the `pub get` docker step failing. 

An explanation has been given to why this might happen (mainly, VirtualBox VMs not keeping track of local time when going to sleep mode). 

@lukechurch Is this issue still happening? Does rebooting the boot2docker VM help?

I'll close this bug for now, since we cannot do anything about that in `package:appengine` to fix this issue.

**Closed by mkustermann** 2015-02-20 12:22 UTC
